<?php

/**
 * Projects4Me Copyright (c) 2017. Licensing : http://legal.projects4.me/LICENSE.txt. Do not remove this line
 */

namespace Gaia\Libraries\Oauth\Storage;

/**
 * This class extends Pdo class provided by bshaffer/oauth2-server-php library. In this class we're overriding
 * checkPassword and hashPassword method in order to follow our hashing functionality. By default hashPassword method
 * use "sha1" algorithm in order to match user password. But we have changed the encryption of user password using
 * "bcrypt" alogrithm to add more security. So now we need to match the hash generated by bcrypt algorithm. That's why
 * we needed to override these methods.
 * 
 * @author Rana Nouman <ranamnouman@gmail.com>
 */
class Pdo extends \OAuth2\Storage\Pdo
{

    /**
     * Fetches a user record by email address instead of username.
     *
     * bshaffer passes whatever was supplied as "username" in the token request
     * straight into this method. Because we accept an email field from the
     * client and remap it to "username" before the grant type runs, the value
     * arriving here is always an email address.
     *
     * user_id is set to the email so that the access-token row carries the
     * email; RestController resolves the current user with:
     *   User::findFirst("email = '$token->user_id'")
     *
     * @param  string $email
     * @return array|false
     */
    public function getUser($email)
    {
        $stmt = $this->db->prepare(
            sprintf('SELECT * FROM %s WHERE email = :email', $this->config['user_table'])
        );
        $stmt->execute(['email' => $email]);

        if (!$userInfo = $stmt->fetch(\PDO::FETCH_ASSOC)) {
            return false;
        }

        return array_merge(['user_id' => $userInfo['email']], $userInfo);
    }

    /**
     * This function checks user password.
     *
     * @param array $user
     * @param string $password
     * @return string
     */
    protected function checkPassword($user, $password)
    {
        return $user['password'] = $this->hashPassword($password, $user['password']);
    }

    /**
     * This function matches stored hash of the password with the password input by user.
     *
     * @param string $password  Input given by user.
     * @param string $passwordHash  Hash of password stored in database.
     * @return string
     */
    protected function hashPassword($password, $passwordHash = null)
    {
        if (password_verify($password, $passwordHash)) {
            return $passwordHash;
        }
    }
}