name: Run Gaia test cases

on:
  pull_request:
    types: [opened]

  push:
    branches:
      - 'ci/cd'

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/gaia:1.0.0
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3
    - name: Run test cases
      run: |
        phpunit tests